# This workflow will build a package using Gradle and then publish it to GitHub packages when a release is created

name: Build docker GHCR

on: 
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
         registry: ghcr.io
         username: pChocz
         password: ${{ secrets.GH_PAT }}

      - name: build and push the image
        run: |
          docker build . --tag ghcr.io/pchocz/homepage:latest
          docker push ghcr.io/pchocz/homepage:latest
